# src/overlays/k0s.nix
# k0sctl pinned to tip-of-spear, independent of nixpkgs channel drift.
#
# Both nixpkgs channels lag upstream k0sctl releases, so channel-tracking
# cannot hold the tip — this overlay asserts the version. If a channel
# catches up, the pin builds the same version and stays a harmless no-op.
# The derivation mirrors upstream nixpkgs pkgs/by-name/k0/k0sctl/package.nix.
#
# Version bump procedure:
#   1. src/lib/versions.nix — kubernetes.k0sctl.version
#   2. this file — src hash + vendorHash for the new tag
#
# The k0s binary itself is NOT defined here — it comes from the k0s-nix
# flake input's overlay (pkgs.k0s, pkgs.k0s_1_27..k0s_1_35), composed in
# ./default.nix. Version selection: src/lib/versions.nix kubernetes.k0s.attr.

let
  versions = import ../lib/versions.nix;
  inherit (versions.kubernetes) k0sctl;
in

# final (not prev) for buildGoModule: k0sctl ≥0.31.1 requires go >= 1.26
# (go.mod toolchain directive), newer than nixos-25.11's Go 1.25.10. The
# unstable package set — attached later in the overlay list, reachable here
# through the fixpoint — carries the toolchain upstream nixpkgs builds this
# package with.
final: prev: {
  k0sctl = final.unstable.buildGoModule rec {
    pname = "k0sctl";
    inherit (k0sctl) version;

    src = prev.fetchFromGitHub {
      owner = "k0sproject";
      repo = "k0sctl";
      tag = "v${version}";
      hash = "sha256-AbSHyc+Orclm2Cun9QTBqC5AxN1+QOveNzBqzX62vBA=";
    };

    vendorHash = "sha256-zc/6fC6VQJp7g2URWivaGW0APVHMa+uyHlBPM4b0bf8=";

    ldflags = [
      "-s"
      "-w"
      "-X=github.com/k0sproject/k0sctl/version.Environment=production"
      # versioninfo.Version doesn't take effect; upstream quirk:
      # https://github.com/carlmjohnson/versioninfo/discussions/12
      "-X=github.com/carlmjohnson/versioninfo.Version=v${version}"
      "-X=github.com/carlmjohnson/versioninfo.Revision=v${version}"
    ];

    nativeBuildInputs = [ prev.installShellFiles ];

    # Completions are generated by executing the freshly built binary;
    # valid for native builds (all konductor k0sctl consumers are native).
    postInstall = ''
      for shell in bash zsh fish; do
        installShellCompletion --cmd ${pname} \
          --$shell <($out/bin/${pname} completion --shell $shell)
      done
    '';

    passthru.tests.version = prev.testers.testVersion {
      package = final.k0sctl;
      command = "k0sctl version";
      # versioninfo.Version ldflags don't take effect; upstream quirk:
      # https://github.com/carlmjohnson/versioninfo/discussions/12
      version = "version: (devel)\ncommit: v${version}\n";
    };

    meta = with prev.lib; {
      description = "Bootstrapping and management tool for k0s clusters";
      homepage = "https://k0sproject.io/";
      changelog = "https://github.com/k0sproject/k0sctl/releases/tag/v${version}";
      license = licenses.asl20;
      mainProgram = "k0sctl";
    };
  };
}
