# src/config/shell/ssh.nix
# Hermetic SSH wrapper for Konductor VM access
#
# Design rationale (informed by OpenSSH documentation):
# - OpenSSH has NO native SSH_CONFIG environment variable
# - The only way to force alternate config is via -F flag
# - SSH Include directive supports ${HOME} and %d tokens
# - First match wins in SSH config processing order
# - Missing Include files are gracefully ignored (not fatal)
#
# Solution:
# - Generate ephemeral config at /tmp/konductor-ssh/config
# - Our localhost VM entry comes FIRST (takes priority)
# - Include user's ~/.ssh/config for their other hosts
# - Wrapper uses -F to force our generated config
# - Completely hermetic: zero writes to ~/.ssh/
#
# Exports:
#   package   - Wrapped ssh binary that uses KONDUCTOR_SSH_CONFIG
#   shellHook - Generates SSH config at shell entry time
#   env       - Environment variables (KONDUCTOR_SSH_CONFIG)
#   configPath - Default path for generated config

{ pkgs, ... }:

let
  # Default location for generated SSH config
  defaultConfigPath = "/tmp/konductor-ssh/config";

  # Shell code to generate SSH config (used by shellHook)
  # This is the single source of truth for SSH config generation
  generateConfigScript = ''
    # Generate SSH config for VM access (hermetic - no writes to ~/.ssh/)
    _konductor_ssh_config="''${KONDUCTOR_SSH_CONFIG:-${defaultConfigPath}}"
    _konductor_ssh_dir="$(dirname "$_konductor_ssh_config")"

    # Detect SSH identity file, or generate ephemeral key if none exists
    _ssh_identity=""
    if [[ -f "$HOME/.ssh/id_ed25519" ]]; then
      _ssh_identity="$HOME/.ssh/id_ed25519"
    elif [[ -f "$HOME/.ssh/id_rsa" ]]; then
      _ssh_identity="$HOME/.ssh/id_rsa"
    else
      # No user key - generate ephemeral key for this session
      _ephemeral_key="$_konductor_ssh_dir/id_ed25519"
      if [[ ! -f "$_ephemeral_key" ]]; then
        mkdir -p "$_konductor_ssh_dir"
        ssh-keygen -t ed25519 -f "$_ephemeral_key" -N "" -q
      fi
      _ssh_identity="$_ephemeral_key"
    fi

    # Export public key path for cloud-init and other automation
    export KONDUCTOR_SSH_PUBKEY="$_ssh_identity.pub"

    # Always generate config - we always have a key now
    mkdir -p "$_konductor_ssh_dir"
    cat > "$_konductor_ssh_config" << SSHCONFIG
# Konductor VM SSH Configuration
# Auto-generated by devshell on: $(date -Iseconds)
# User: $USER (uid $(id -u))
#
# Design: First match wins. Our localhost entry takes priority.
# User's ~/.ssh/config is included for their other hosts.

Host localhost
    HostName localhost
    Port 2222
    User $USER
    IdentityFile $_ssh_identity
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null
    LogLevel ERROR
    ConnectTimeout 5

# Include user's SSH config for their other hosts
# Missing file is gracefully ignored (not an error)
Include %d/.ssh/config
SSHCONFIG
    chmod 600 "$_konductor_ssh_config"
    unset _konductor_ssh_config _konductor_ssh_dir _ssh_identity _ephemeral_key
  '';

in
{
  # Wrapped ssh that uses KONDUCTOR_SSH_CONFIG when available
  # Falls back to unwrapped ssh if env var unset or file missing
  package = pkgs.writeShellApplication {
    name = "ssh";
    runtimeInputs = [ pkgs.openssh ];
    text = ''
      # Use KONDUCTOR_SSH_CONFIG if set and file exists
      # The generated config includes user's ~/.ssh/config via Include directive
      if [[ -n "''${KONDUCTOR_SSH_CONFIG:-}" && -f "''${KONDUCTOR_SSH_CONFIG}" ]]; then
        exec ssh -F "''${KONDUCTOR_SSH_CONFIG}" "$@"
      else
        exec ssh "$@"
      fi
    '';
  };

  unwrapped = pkgs.openssh;

  # ShellHook to generate SSH config at devshell entry
  # Use in devshells: ${config.shell.ssh.shellHook}
  shellHook = generateConfigScript;

  # Environment variables for devshells
  env = {
    KONDUCTOR_SSH_CONFIG = defaultConfigPath;
  };

  # Export the default path for reference
  configPath = defaultConfigPath;

  # No static config file - generated dynamically
  configFile = null;

  meta = {
    description = "SSH with Konductor VM config support";
    configurable = true;
    envVar = "KONDUCTOR_SSH_CONFIG";
    defaultPath = defaultConfigPath;
  };
}
