name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    name: Flake Check ${{ matrix.system }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - system: x86_64-linux
            runner: ubuntu-24.04
    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v15
        with:
          name: braincraftio
          authToken: ${{ secrets.BCIO_CACHIX_PRIVATE_KEY }}

      - name: Run flake checks
        run: nix flake check --accept-flake-config -L

      - name: Build installable package
        run: nix build .#packages.x86_64-linux.default --accept-flake-config -L
